config/routes.rb
Rails.application.routes.draw do

  resources :offers
  resources :travels, except: [:index] do
    resources :opinions, except: [:index]
  end
  resources :trips
  
  devise_for :users
  devise_scope :user do
    get 'profile/edit' => 'users#edit'
  end

  resources :ideas
  resources :articles
  resources :users, only: [:index, :show, :update]
  resources :jobs, except: [:index] do
    resources :recommendations
  end
  resources :sectors

  root 'static_pages#home'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

end

app/models/sector.rb
# encoding: utf-8
class Sector < ActiveRecord::Base
  
  # Associations
  has_many :jobs
  has_many :offers
  
    # Validations
  
  # Callbacks

  # Instance methods
  def to_s
    code  
  end
end

app/controllers/sectors_controller.rb
# encoding: utf-8
class SectorsController < ApplicationController
  load_and_authorize_resource

  def new
    # @sector = current_user.sectors.build
  end

  def edit
    # @sector = Sector.find(params[:id])
  end

  def create
    # @job = current_user.jobs.build(params[:id])
    if @sector.save
      redirect_to sectors_path, notice: 'Sector was successfully created.'
    else
      render :new
    end
  end

  def update
  if @sector.update(sector_params)
      redirect_to sectors_path, notice: 'Sector was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # @job = Job.find(params[:id])
    @sector.destroy
    redirect_to sectors_path, notice: 'Sector was successfully destroyed.'
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def sector_params
    params.require(:sector).permit(:code)
  end
end

app/views/sectors/_form.html.haml
= simple_form_for(@sector) do |s|

  = s.input :code
  = s.submit

app/views/sectors/_sector.html.haml
.sector.table
  %td
    = sector.code
    %br
    = link_to "Edit", edit_sector_path(sector)

app/views/sectors/edit.html.haml
%h1 Create a sector

= render 'form'

= link_to "Back", root_path

app/views/sectors/index.html.haml
-provide(:title, "Sectors")
%h1 All sectors

%table.table
  %thead
    %tr
      %th
      %th Name

  %tbody
    - @sectors.each do |sector|
      %tr
        %td= link_to 'X', sector, :method => :delete, :data => { :confirm => 'Are you sure?' }
        %td= link_to sector.code, edit_sector_path(sector)
                
%p
  = link_to "Add a sector", new_sector_path
  

app/views/sectors/new.html.haml
- provide(:title, 'Create a sector')

%h1 New sector

= render 'form'
= link_to 'Back', users_path