config/routes.rb
Rails.application.routes.draw do

  resources :offers
  resources :travels, except: [:index] do
    resources :opinions, except: [:index]
  end
  resources :trips
  
  devise_for :users
  devise_scope :user do
    get 'profile/edit' => 'users#edit'
  end

  resources :ideas
  resources :articles
  resources :users, only: [:index, :show, :update]
  resources :jobs, except: [:index] do
    resources :recommendations
  end
  resources :sectors

  root 'static_pages#home'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

end

app/models/user.rb
# encoding: utf-8
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_many :jobs 
  has_many :travels
  belongs_to :employer
  has_many :offers, foreign_key: "created_by_id"
  has_many :trips
  has_attached_file :avatar, styles: { 
    thumb: '100x100>', 
    square: '200x200#', 
    medium: '300x300>' 
  }, 
  :storage => :s3, 
  :s3_credentials => "#{Rails.root}/.env",
  :path => ":attachment/:id/:style.:extension",
  :bucket => "myaustralianbookbucket"
  
  # Validations

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-_.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  
  validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  
  # Callbacks
  before_create :set_user_name
  
  # Instance methods
  
  def to_s
    name
  end
    
  protected
  
  def set_user_name
    if name.blank? && email.present?
      self.name = email.split('@').first.capitalize
    end
  end
 
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  
  load_and_authorize_resource

  def index
  end

  def show
  end

  def edit
  end
  
  def new
  end
    
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Your profile was successfully updated'
    else
      render :edit
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(
      :name, :email, :country, :birth, :phone, :driving_licence, :linkedin_url,
      :current_location, :headline, :about_me, :skills, :avatar, :sector, :languages, :computer_skills
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for(current_user, multipart: true) do |f|
  
  .row
    .col-md-4
      .subtitle
        %h4 main information
      %br
      .edit-avatar
        = "Upload a profile picture"
        = f.file_field :avatar
      %br
      .edit-form
        = f.input :name, label: "First Name and Last Name", placeholder: "Ex: John Doe"
        = f.input :email, label: "Email address", placeholder: "Ex: john.doe@example.com"
        = f.input :phone, as: :tel, label: "Phone number", placeholder: "+61 08 9341 6843"
        = f.input :birth, as: :string, label: "Date of birth", input_html: {class: 'birthday-picker'}
        = f.input :country, label: "Country of origin"
        = f.input :current_location, label: "Current location", placeholder: "Ex: Sydney"
        = f.input :driving_licence, label: "Do you have a driving licence? Tick for yes!"
    
    .col-md-8
      .subtitle
        %h4 professional information
      %br
      .edit-form
        = f.input :headline, label: "Main job title", placeholder: "Ex: Barman"
        = f.input :about_me, label: "About - Profile description", placeholder: "Ex: Holding a Working-Holiday Visa, I am looking for job opportunities around Australia. I am a dynamic, motivated and fast-learning person with good communication and presentation skills etc."
        = f.input :sector, label: "Prefered sectors of activity", placeholder: "Ex: Hotel, restaurants"
        = f.input :skills, label: "Skills"
        = f.input :computer_skills
        = f.input :languages
        = f.input :linkedin_url, label: "Link your profile to your Linkedin account!"
    
      .edit-actions
        = f.submit 'Update', class: 'btn btn-info', data: { disable_with: "Please wait..." }
        %br

app/views/users/_main_part.html.haml
.right-information
  .user-name
    %h1.strong 
      = @user.name
  .well.well-lg.about
    .about-me
      %strong About me
    .about-me-text
      = @user.about_me
  
  - if can? :edit, @user 
    = link_to profile_edit_path, class: "btn btn-default" do
      %b.fa.fa-pencil-square-o
      Edit my profile
  - if can? :edit, @user
    = link_to edit_user_registration_path(@user), class: "btn btn-default" do
      %b.fa.fa-lock
      Edit my login information
  %br
  
  .experiences  
    %h2 Latest experiences
    - if can? :edit, @user
      .add
        .row
          .col-xs-6
            = link_to 'Add a job', new_job_path, class: "btn btn-info"
          .col-xs-6
            = link_to 'Add a travel', new_travel_path, class: "btn btn-warning"
    %br
    .render-jobs
      = render @user.jobs.reverse
    %br
    .render-travels
      = render @user.travels.reverse
  
    .back
      = link_to 'Back', root_path, class: "btn btn-default"

app/views/users/_sidebar.html.haml
.left-information
  .well.picture
    - if @user.avatar
      .user.image
        = image_tag @user.avatar.url(:square), :size => '150x150'
    - else 
      = "Click here to add a picture"

  .sidebox.information
    .left-title
      main information
    .job-information
      .birth
        - if @user.birth
          Born on
          #{@user.birth.strftime("%d %B %Y")}
      .location
        %b.fa.fa-map-marker
        - if @user.current_location.blank?
          On the road
        - else
          = @user.current_location
      .email
        - if @user.email
          %b.fa.fa-envelope
          = @user.email    
      .phone
        - if @user.phone
          %b.fa.fa-phone
          = @user.phone
      .driving
      - if @user.driving_licence
        %b.fa.fa-car
        Driving Licence 

  .sidebox.sectors
    .left-title
      sectors  
    %br
    .content
      - if @user.sector
        = @user.sector
      - else
        - if can? :edit, @user
          = link_to profile_edit_path, class: "btn btn-default" do
            %b.fa.fa-pencil-square-o
            Add sectors

  .sidebox.skills
    .left-title
      skills
    %br  
    .content
      - if @user.skills
        = @user.skills
      - else
        - if can? :edit, @user
          = link_to profile_edit_path, class: "btn btn-default" do
            %b.fa.fa-pencil-square-o
            Add skills
  
  .sidebox.languages
    .left-title
      Languages
    %br
    .content
      - if @user.languages
        = @user.languages
      - else
        - if can? :edit, @user
          = link_to profile_edit_path, class: "btn btn-default" do
            %b.fa.fa-pencil-square-o
            Add languages
  
  .sidebox.computer
    .left-title
      computer skills
    %br
    .content
      - if @user.computer_skills
        = @user.computer_skills
      - else
        - if can? :edit, @user
          = link_to profile_edit_path, class: "btn btn-default" do
            %b.fa.fa-pencil-square-o
            Add computer skills

app/views/users/edit.html.haml
.page-title
  %h1 Your profile
	
= render 'form'
= link_to "See my profile", user_path(current_user), class: 'btn btn-default' 
= link_to "Back", root_path, class: 'btn btn-default'

app/views/users/index.html.haml
-provide(:title, "Users")
%h1 Liste des PVTistes en Australie

%table.table
  %thead
    %tr
      %th Name
      %th Email
      %th Job

  %tbody
    - @users.each do |user|
      %tr
        %td
          = user.name
          = link_to "Profile",  user_path(user)
          - if can? :update, user
            = link_to 'Edit', edit_user_registration_path(user)
          - if can? :destroy, user
            = link_to 'X', user, :method => :delete, :data => { :confirm => 'Are you sure?' }
        %td= user.email
        %td= user.headline

app/views/users/show.html.haml
- provide(:title, "My profile")

.row 
  .col-sm-3
    = render 'sidebar'
  .col-sm-9
    = render 'main_part'