config/routes.rb
Rails.application.routes.draw do

  resources :offers
  resources :travels, except: [:index] do
    resources :opinions, except: [:index]
  end
  resources :trips
  
  devise_for :users
  devise_scope :user do
    get 'profile/edit' => 'users#edit'
  end

  resources :ideas
  resources :articles
  resources :users, only: [:index, :show, :update]
  resources :jobs, except: [:index] do
    resources :recommendations
  end
  resources :sectors

  root 'static_pages#home'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

end

app/models/ability.rb
# encoding: utf-8
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    if user.admin?
      can :manage, :all
    end

    can :read, User
    can :manage, User, id: user.id

    can :manage, Job, user_id: user.id
    
    can :create, Recommendation
    
    can :create, Opinion
    
    can :manage, Travel, user_id: user.id
    
    can [:index], Trip
    can [:create, :read, :update, :destroy], Trip, user_id: user.id
    
    can [:read, :create], Employer
    
    can [:index, :create], Offer
    can [:update, :destroy], Offer, created_by_id: user.id   
    
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/employer.rb
# encoding: utf-8
class Employer < ActiveRecord::Base
  
  # Associations
  has_many :contacts, class_name: 'User', dependent: :destroy
  accepts_nested_attributes_for :contacts
  has_many :jobs
  has_many :offers
  
  # Validations
  validates :name, presence: true
  
  # Callbacks

  # Instance methods
  def to_s 
    name
  end 

end

app/models/idea.rb
class Idea < ActiveRecord::Base
end

app/models/job.rb
# encoding: utf-8
class Job < ActiveRecord::Base
  
  # Associations
  
  belongs_to :user 
  belongs_to :employer
  belongs_to :sector
  has_many :recommendations
  accepts_nested_attributes_for :employer

  # Validations
  
  # Callbacks

  # Instance methods
  delegate :city, :name, :location, to: :employer, prefix: false, allow_nil: true
  delegate :code, to: :sector, prefix: false, allow_nil: true
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
end

app/models/offer.rb
# encoding: utf-8
class Offer < ActiveRecord::Base
  
  # Associations
  
  belongs_to :employer
  accepts_nested_attributes_for :employer
  belongs_to :sector
  belongs_to :created_by, class_name: 'User'
  
  # Instance methods

  delegate :city, :name, :location, :contact_point, to: :employer, prefix: false, allow_nil: true
  delegate :code, to: :sector, prefix: false, allow_nil: true

  def self.search(search)
    if search.present?
      joins(:sector, :employer)
      .where('position LIKE :q OR sectors.code LIKE :q OR employers.city LIKE :q OR employers.name LIKE :q OR employers.location LIKE :q', q:"%#{search}%")
    else
      where(true)
    end
  end

end

app/models/opinion.rb
# encoding: utf-8
class Opinion < ActiveRecord::Base
  
  # Associations
  
  after_create :set_token
  belongs_to :travel
    
  # Validations

  # Callbacks

  # Instance methods
 
 private
  
  def set_token
    self.authentication_token = SecureRandom.hex
    self.save
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/recommendation.rb
# encoding: utf-8
class Recommendation < ActiveRecord::Base
  
  # Associations
  
  after_create :set_token
  belongs_to :job
    
  # Validations

  # Callbacks

  # Instance methods
    
  private
  
  def set_token
    self.authentication_token = SecureRandom.hex
    self.save
  end
  
end

app/models/sector.rb
# encoding: utf-8
class Sector < ActiveRecord::Base
  
  # Associations
  has_many :jobs
  has_many :offers
  
    # Validations
  
  # Callbacks

  # Instance methods
  def to_s
    code  
  end
end

app/models/travel.rb
# encoding: utf-8
class Travel < ActiveRecord::Base
  
  # Associations
 
  belongs_to :user 
  has_many :opinions
  
  # Validations

  # Callbacks

  # Instance methods
  
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  
  # Associations
  
  belongs_to :user
  
  # Instance methods
  
  def to_s 
    name
  end
  
  def self.search(search)
    if search.present?
      where('name LIKE :q OR departure_point LIKE :q OR arrival_point LIKE :q', q:"%#{search}%")
    else
      where(true)
    end
  end
end

app/models/user.rb
# encoding: utf-8
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_many :jobs 
  has_many :travels
  belongs_to :employer
  has_many :offers, foreign_key: "created_by_id"
  has_many :trips
  has_attached_file :avatar, styles: { 
    thumb: '100x100>', 
    square: '200x200#', 
    medium: '300x300>' 
  }, 
  :storage => :s3, 
  :s3_credentials => "#{Rails.root}/.env",
  :path => ":attachment/:id/:style.:extension",
  :bucket => "myaustralianbookbucket"
  
  # Validations

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-_.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  
  validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  
  # Callbacks
  before_create :set_user_name
  
  # Instance methods
  
  def to_s
    name
  end
    
  protected
  
  def set_user_name
    if name.blank? && email.present?
      self.name = email.split('@').first.capitalize
    end
  end
 
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/layout_helper.rb
# encoding: utf-8
module LayoutHelper

  def alert_class(flash_type)
    case flash_type
    when "alert", "error"
      "alert-danger"
    when "notice"
      "alert-success"
    else
      "alert-#{flash_type}"
    end
  end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
  def offer_image(offer)
    sector_code = offer.sector.code
    if sector_code == "Hotel"
      'fa-star'
    elsif sector_code == "Bar"
      'fa-beer'
    elsif sector_code == "Farming"
      'fa-tree'
    elsif sector_code == "Volunteering"
      'fa-thumbs-o-up'
    elsif sector_code == "NGOs"
      'fa-globe'
    elsif sector_code == "Events"
      'fa-calendar-check-o'
    elsif sector_code == "Sales"
      'fa-usd'
    elsif sector_code == "Babysitting"
      'fa-gamepad'
    elsif sector_code == "Au-pair"
      'fa-home'
    elsif sector_code == "Maid"
      'fa-bed'
    elsif sector_code == "Restaurant"
      'fa-cutlery'
    elsif sector_code == "Coffee"
      'fa-coffee'
    elsif sector_code == "Jet fighting"
      'fa-fighter-jet'
    elsif sector_code == "Construction"
      'fa-building-o'
    elsif sector_code == "Other"
      'fa-fa-odnoklassniki'
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |message_type, message|
  %div{:class => "alert #{alert_class(message_type)}"}
    = link_to '×', '#', class: 'close', data: {dismiss: 'alert'}
    = message.html_safe

app/views/layouts/_footer.html.haml
%footer.footer
  .line-footer
    = link_to "About us", about_path
    = " | "
    = link_to "Contact", contact_path    
    = " | "
    = link_to "Travel offers", trips_path
    = " | "
    = link_to "Job offers", jobs_path
    = " | "
    Terms & conditions 
    = " | "
    Confidentiality

    

app/views/layouts/_head.html.haml
%head
  %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %meta{:content => "RUAgFR4IY2BT07EV6ThG1lpKTidAYnPrhkaoRSYwVs4", :name => "google-site-verification"}/
  %meta{:charset => "UTF-8"}/
  %title= full_title(yield(:title))
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  = render 'layouts/shim'

app/views/layouts/_header.html.haml
%header.header-fixed-top

      

app/views/layouts/_home_header.html.haml
%header.header-fixed-top
  .header
    .header.name
      %h1
        Travelling Bees
    .header.surname
      %h4
        The tailor-made app for a Working Holiday Visa
    
      

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle{type: "button", data: {toggle: "collapse", target: "#myNavbar"}}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Home", root_path, id: "logo", class: "navbar-brand"
    #myNavbar.collapse.navbar-collapse
      - if !user_signed_in?
        .navbar-right{style: "margin-right: 0; text-align: center;"}
          = link_to "Log in", new_user_session_path, class: 'btn btn-info navbar-btn', id: 'loginBtn'
      %ul.nav.navbar-nav.navbar-right{style: "margin: 0 15px"}
        %li= link_to "About", about_path
        %li= link_to "Travel offers", trips_path
        %li= link_to "Job offers", offers_path
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: '#'}
              %span= current_user.name
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Edit my profile", profile_edit_path(current_user)
              %li= link_to "My profile", user_path(current_user)
              %li.divider
              %li= link_to "Log out", destroy_user_session_path, method: :delete

app/views/layouts/_navbar_admin.html.haml
%nav.navbar-collapse
  .container-fluid
    .navbar-header
      %button.navbar-toggle{type: "button", data: {toggle: "collapse", target: ".navbar-collapse"}}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Sector", sectors_path
        %li= link_to "Users", users_path
        %li= link_to "Job offers", offers_path
        %li= link_to "Contact", contact_path
        %li= link_to "Travel offers", trips_path
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: '#'}
            %span= current_user.name
            %b.caret
          %ul.dropdown-menu
            %li= link_to "Edit my profile", profile_edit_path
            %li= link_to "My profile", user_path(current_user)
            %li.divider
            %li= link_to "Log out", destroy_user_session_path, method: :delete

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/head'
  %body
    .wrapper
      .header
        %before
        - if current_page?(root_path)
          = render 'layouts/home_header'
        - else 
          = render 'layouts/header'
        %after
        = render 'layouts/navbar_admin' if user_signed_in? && current_user.admin?
      = render 'layouts/navbar'
      .container
        = render 'layouts/flash_messages'
        = yield
      .footer
        = render 'layouts/footer'